/**
 * Configuration centralisée des icônes Font Awesome
 *
 * Ce fichier importe uniquement les icônes utilisées dans l'application
 * au lieu de charger toute la bibliothèque (~7000 icônes).
 *
 * Pour ajouter une nouvelle icône :
 * 1. Importer l'icône depuis le package approprié
 * 2. L'ajouter à l'appel library.add()
 *
 * Nommage : les icônes kebab-case deviennent camelCase avec préfixe 'fa'
 * Exemple : 'chevron-left' -> faChevronLeft
 */

import { library } from '@fortawesome/fontawesome-svg-core'

// Solid icons (fas)
import {
  faAnglesLeft,
  faAnglesRight,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowsRotate,
  faAt,
  faBars,
  faBed,
  faBell,
  faBox,
  faBoxOpen,
  faBuilding,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faCalendarMinus,
  faCalendarPlus,
  faCalendarWeek,
  faCalendarXmark,
  faCamera,
  faCar,
  faCoins,
  faCheck,
  faCreditCard,
  faCheckCircle,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardList,
  faClock,
  faCloudArrowUp,
  faCloudUploadAlt,
  faCog,
  faComment,
  faDownload,
  faEnvelope,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFile,
  faFilter,
  faFilterCircleXmark,
  faGlobe,
  faGripVertical,
  faHashtag,
  faImages,
  faInbox,
  faInfoCircle,
  faKey,
  faList,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMinus,
  faMobileAlt,
  faMobileScreen,
  faMobileScreenButton,
  faMousePointer,
  faPause,
  faPen,
  faPenToSquare,
  faPlay,
  faPlayCircle,
  faPlus,
  faPlusSquare,
  faRotate,
  faRotateLeft,
  faSearch,
  faShieldAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faStop,
  faSun,
  faTachometerAlt,
  faTag,
  faTags,
  faTimes,
  faTimesCircle,
  faTools,
  faTrash,
  faTrashAlt,
  faTruck,
  faUpload,
  faUser,
  faUserPen,
  faUsers,
  faUserShield,
  faVolumeHigh,
  faVolumeXmark,
  faWrench,
  faXmark
} from '@fortawesome/free-solid-svg-icons'

// Brand icons (fab)
import {
  faAndroid,
  faApple
} from '@fortawesome/free-brands-svg-icons'

/**
 * Enregistre toutes les icônes utilisées dans l'application
 * Appelé une seule fois au démarrage depuis main.ts
 */
export function registerIcons(): void {
  library.add(
    // Solid icons
    faAnglesLeft,
    faAnglesRight,
    faArrowLeft,
    faArrowRight,
    faArrowRightFromBracket,
    faArrowsRotate,
    faAt,
    faBars,
    faBed,
    faBell,
    faBox,
    faBoxOpen,
    faBuilding,
    faCalendar,
    faCalendarAlt,
    faCalendarCheck,
    faCalendarDay,
    faCalendarDays,
    faCalendarMinus,
    faCalendarPlus,
    faCalendarWeek,
    faCalendarXmark,
    faCamera,
    faCar,
    faCoins,
    faCheck,
    faCheckCircle,
    faCreditCard,
    faCheckDouble,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faClipboardList,
    faClock,
    faCloudArrowUp,
    faCloudUploadAlt,
    faCog,
    faComment,
    faDownload,
    faEnvelope,
    faExclamationCircle,
    faExclamationTriangle,
    faEye,
    faEyeSlash,
    faFile,
    faFilter,
    faFilterCircleXmark,
    faGlobe,
    faGripVertical,
    faHashtag,
    faImages,
    faInbox,
    faInfoCircle,
    faKey,
    faList,
    faLocationDot,
    faLock,
    faMagnifyingGlass,
    faMagnifyingGlassMinus,
    faMagnifyingGlassPlus,
    faMinus,
    faMobileAlt,
    faMobileScreen,
    faMobileScreenButton,
    faMousePointer,
    faPause,
    faPen,
    faPenToSquare,
    faPlay,
    faPlayCircle,
    faPlus,
    faPlusSquare,
    faRotate,
    faRotateLeft,
    faSearch,
    faShieldAlt,
    faSort,
    faSortDown,
    faSortUp,
    faSpinner,
    faStar,
    faStop,
    faSun,
    faTachometerAlt,
    faTag,
    faTags,
    faTimes,
    faTimesCircle,
    faTools,
    faTrash,
    faTrashAlt,
    faTruck,
    faUpload,
    faUser,
    faUserPen,
    faUsers,
    faUserShield,
    faVolumeHigh,
    faVolumeXmark,
    faWrench,
    faXmark,
    // Brand icons
    faAndroid,
    faApple
  )
}
